"""Render one bilingual text line per project; retain the folded Other section."""
from __future__ import annotations

from html import escape
import re

FEATURED_COUNT = 6


def validate_projects(projects: list[dict]) -> None:
    if not isinstance(projects, list) or not projects:
        raise ValueError("Expected a non-empty curated project list")
    seen = set()
    for project in projects:
        if not isinstance(project, dict):
            raise ValueError("Each project must be an object")
        for key in ("repo", "name", "en", "zh"):
            value = project.get(key)
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"Missing project field: {key}")
            if any(c in value for c in "\r\n"):
                raise ValueError(f"Project fields must stay on one line: {key}")
        repo = project["repo"]
        if not re.fullmatch(r"yuxino/[A-Za-z0-9_.-]+", repo) or repo.lower() in seen:
            raise ValueError("Invalid or duplicate repository")
        seen.add(repo.lower())


def rank_projects(projects: list[dict], counts: dict[str, int]) -> list[dict]:
    validate_projects(projects)
    if set(counts) != {p["repo"] for p in projects}:
        raise ValueError("Star snapshot does not match the curated project list")
    if any(type(n) is not int or n < 0 for n in counts.values()):
        raise ValueError("Expected non-negative integer star counts")
    return sorted(projects, key=lambda p: (-counts[p["repo"]], p["name"].casefold(), p["repo"].casefold()))


def render_project(project: dict) -> str:
    """Use normal, wrapping text; no cards, badges, counts or website links."""
    name, en, zh = (escape(project[key]) for key in ("name", "en", "zh"))
    repo = escape(project["repo"], quote=True)
    return f'<a href="https://github.com/{repo}"><strong>{name}</strong></a> — {en} / {zh}'


def render_group(projects: list[dict]) -> str:
    return "<p>\n" + "<br>\n".join(render_project(p) for p in projects) + "\n</p>"


def render_readme(intro: str, ranked: list[dict], footer: str = "") -> str:
    lines = [
        "<!-- Generated by scripts/update_stars.py. Edit profile/*.md and profile/projects.json. -->",
        "", intro.strip(), "",
        '<p align="center"><sub>PROJECTS / 项目</sub></p>', "",
        render_group(ranked[:FEATURED_COUNT]), "",
    ]
    others = ranked[FEATURED_COUNT:]
    if others:
        lines += [
            "<details>", "<summary>Other projects / 其他项目</summary>", "",
            render_group(others), "", "</details>", "",
        ]
    if footer.strip():
        lines += [footer.strip(), ""]
    return "\n".join(lines)


def build_outputs(intro: str, projects: list[dict], counts: dict[str, int], date: str, footer: str = "") -> dict[str, str]:
    # Keep the updater's interface. Counts determine order only; neither the
    # counts nor the refresh date is displayed. The snapshot stays in JSON.
    ranked = rank_projects(projects, counts)
    return {"README.md": render_readme(intro, ranked, footer)}
